spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/capacitacion_db
    username: sisapp
    password: sisapp98
  logging:
    level:
      net.sf.jasperreports.extensions: DEBUG
      net.sf.jasperreports.engine.fonts: DEBUG
server:
  port: 8088